import type { Metadata } from "next";
import "./globals.css";
import ThemeContext from "@/providers/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-[#f8fafc] dark:bg-background">
        <ThemeContext>{children}</ThemeContext>
      </body>
    </html>
  );
}
